Add a footer to the website that credits CGDS
uab-cgds-worthey/rosalution pull request #29
Opened 2023-01-12 23:02 UTC by kuthedk

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] My code follows the style guidelines enforced by static analysis tools.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.

## Pull Request Details

Wrike Ticket - [On the frontned, add a tiny footer that credits CGDS developing Rosalution](https://www.wrike.com/open.htm?id=1033379957)

Changes made:

New component AppFooter.vue
- Created a new vue component named AppFooter

App.vue
- Added a new component, `AppFooter` inside the template and enclosed router-view inside a div 

main.js
- A new component `AppFooter` was imported from ./components/AppFooter.vue and registered as a component.
- The component `AppFooter` is added as a global component.

**To Review:**

- [ ] Static Analysis by Reviewer
- [ ] Clicking on the footer takes you to https://github.com/uab-cgds-worthey/rosalution/blob/main/COPYING
- [ ] All Github Actions checks have passed.

### Screenshots
![image](https://user-images.githubusercontent.com/4248757/212199503-3c91b950-458a-4d54-9ca2-e5390484a750.png)
![image](https://user-images.githubusercontent.com/4248757/212199559-613d3251-d300-468e-9d83-5f5cd4f5b8cd.png)

2023-01-12 23:50 UTC, SeriousHorncat reviewed
Lets chat tomorrow on the specific verbiage that can go in here.  I can get caught up with things going on.

2023-01-12 23:50 UTC, SeriousHorncat commented on frontend/src/components/AppFooter.vue
> +      Copyleft <span class="copy-left">&copy;</span> {{ currentYear }} Center for Computational Genomics and Data
Hmmm, we didn't discuss including the copyleft license in the footer.  This is really interesting.  Have you seen this done somewhere before?  I was just imaging the name of the center, and the fully qualified name of the schoool of medicine.

2023-01-12 23:50 UTC, SeriousHorncat commented on frontend/src/components/AppFooter.vue
> +      Science, UAB School of Medicine
```suggestion
      Science, University of Alabama at Birmingham, Heersink School of Medicine
```

2023-01-13 17:38 UTC, fatimarabab commented
Added a couple of comments to add bottom padding to footer and remove extra unused css class. Otherwise looks good and works as expected.

2023-01-13 17:41 UTC, fatimarabab requested changes

2023-01-13 17:41 UTC, fatimarabab commented on frontend/src/components/AppFooter.vue
> +  width: 100%;
```suggestion
  width: 100%;
  padding-bottom: var(--p-1);
```

2023-01-13 17:41 UTC, fatimarabab commented on frontend/src/components/AppFooter.vue
> +}
```suggestion
```

2023-01-13 17:43 UTC, SeriousHorncat approved these changes

2023-01-13 17:51 UTC, fatimarabab approved these changes

2023-01-13 17:57 UTC, merged