Third party logo link on summary cards
uab-cgds-worthey/rosalution pull request #66
Opened 2023-04-07 23:30 UTC by kuthedk

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] My code follows the style guidelines enforced by static analysis tools.
- [x] If it is a core feature, I have added thorough tests.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.

## Pull Request Details

[Analysis summary page](https://www.wrike.com/open.htm?id=1089167230)

Changes made:

- Added logic to display third-party logos and link out in new tabs if there is a third-party link attached to the analysis

**To Review:**

- [ ] Static Analysis by Reviewer
- [ ] Static Analysis by Reviewer
- [ ] Attach a Monday.com link
  - start from a clean development installation of Rosalution and login as a user
  ``` bash
    # From root of rosalution
    docker compose down
    docker system prune -a --volumes
    docker compose up --build -d
  ```
  - Navigate to [local.rosalution.cgds/rosalution](local.rosalution.cgds/rosalution)
  - Login as a user
  - Click on any Analysis Card.
  - in the Analysis view hover over the vertical 3 dot menu and then click on Attach Monday.com
  ![image](https://user-images.githubusercontent.com/4248757/230643838-4f65fc56-5411-4572-a373-792dbee6754e.png)
  - Observe that a link modal opens up for you to input a link.
  ![image](https://user-images.githubusercontent.com/4248757/229219322-eb243712-5528-41f2-a6a8-b34b76728963.png)
  - Input any text/link and click Add
   ![image](https://user-images.githubusercontent.com/4248757/229219881-d0bda078-067d-422b-b4d4-b50f38a627eb.png)
  - Navigate back to the home page
  - Observer that the monday.com logo now appears at the bottom of the analysis card that you attached a monday.com link to
  ![image](https://user-images.githubusercontent.com/4248757/230691799-75a7f601-b63c-4ac8-9fef-219a1f449a4a.png)
  - Click on the monday.com logo on the card and observer that it opens up a new tab with the link

-  [ ] Attach a PhenoTips link
  -  Repeat the same actions as above except use the Attach PhenoTips menu action. This can be done from the same Analysis that you used for observing attaching a Monday.com link.
- [ ] All Github Actions checks have passed.

### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/4248757/230691521-7d190138-f6fe-4d91-9f13-a7c243cc687a.png)

2023-04-11 14:58 UTC, SeriousHorncat requested changes
The spacing between the bottom of the card & the icons are larger than intended.  Also, the icons are rendered much larger.  I put a side-by-side comparison as a reference below.

![image](https://user-images.githubusercontent.com/1209059/231203523-05703647-c82e-4bca-843f-533fed92631f.png)

2023-04-11 15:45 UTC, kuthedk commented
> The spacing between the bottom of the card & the icons are larger than intended. Also, the icons are rendered much larger. I put a side-by-side comparison as a reference below.
> 
> ![image](https://user-images.githubusercontent.com/1209059/231203523-05703647-c82e-4bca-843f-533fed92631f.png)

As this issue frequently arises, I kindly request access to the design tool to accurately match the intended design, rather than relying on images. If granting access is infeasible, please provide detailed technical specifications for my assigned tasks to ensure I have sufficient information for accurate implementation.

2023-04-13 18:55 UTC, SeriousHorncat commented
Confirmed visual updates are looking as expected.
![image](https://user-images.githubusercontent.com/1209059/231856379-f9f07cc1-5380-4a55-90ba-6fe291e1c8df.png)

2023-04-13 18:55 UTC, SeriousHorncat approved these changes

2023-04-14 15:02 UTC, merged